### ISSUE TITLE
Tried with Android 13, but not work

### ISSUE THREAD

**Issue by SalvatoreNoschese** [Xposed-Modules-Repo/com.github.dan.nostoragerestrict#1]
![Screenshot_20221025-215804_Solid Explorer](https://user-images.githubusercontent.com/16841896/197869893-f212e0fa-14e0-4977-b6b5-e8b063de20e3.png)
Like image. Maybe my error in setup?
Can u help about this?
Ty.

**Comment by SalvatoreNoschese** [comment]
![Screenshot_20221025-215914_File](https://user-images.githubusercontent.com/16841896/197870210-e46b159b-736b-40d5-9b16-e93ef4737d8f.png)

**Comment by DanGLVK** [comment]
The module doesn't make those folders show up in the file picker, I'll try working on that
