### ISSUE TITLE
[BUG]Unable to authorize certain applications

### ISSUE THREAD

**Issue by sakana164** [Xposed-Modules-Repo/com.github.dan.nostoragerestrict#15]
I found that I am unable to authorize some software, such as Discord and Twitch.
I used MT Manager to authorize data through SAF, and then I found that the application package name displayed on the authorization interface was not the one I selected, but the name of the previous successfully authorized application package. As shown in the picture, I chose Discord but it displayed Twitter.
![Screenshot_2024-03-28-13-08-28-247_com google android documentsui](https://github.com/Xposed-Modules-Repo/com.github.dan.nostoragerestrict/assets/76257039/05e76a15-0058-4ee3-92c6-cbe4d873dd4e)
LSPosed log has been uploaded, requesting assistance
[LSPosed_2024-03-28T12_59_27.736206.zip](https://github.com/Xposed-Modules-Repo/com.github.dan.nostoragerestrict/files/14784273/LSPosed_2024-03-28T12_59_27.736206.zip)

**Comment by sakana164** [comment]
hello？are you still there?
I need help

**Comment by DanGLVK** [comment]
> hello？are you still there? I need help

Yes, is the issue still present in version 5.0? If so could you provide a recording?

**Comment by sakana164** [comment]
> > hello？are you still there? I need help
> 
> Yes, is the issue still present in version 5.0? If so could you provide a recording?

Version 5.0，the patch issue in February was what I reported earlier

**Comment by DanGLVK** [comment]
> > > hello？are you still there? I need help
> > 
> > 
> > Yes, is the issue still present in version 5.0? If so could you provide a recording?
> 
> Version 5.0，the patch issue in February was what I reported earlier

Alright, what do you need now?

**Comment by sakana164** [comment]
> > > > hello？are you still there? I need help
> > > 
> > > 
> > > Yes, is the issue still present in version 5.0? If so could you provide a recording?
> > 
> > 
> > Version 5.0，the patch issue in February was what I reported earlier
> 
> Alright, what do you need now?

After the last feedback, I found that most applications can authorize data, but there are still a few applications that cannot be authorized, such as twitch and discord

**Comment by DanGLVK** [comment]
> > > > > hello？are you still there? I need help
> > > > 
> > > > 
> > > > Yes, is the issue still present in version 5.0? If so could you provide a recording?
> > > 
> > > 
> > > Version 5.0，the patch issue in February was what I reported earlier
> > 
> > 
> > Alright, what do you need now?
> 
> After the last feedback, I found that most applications can authorize data, but there are still a few applications that cannot be authorized, such as twitch and discord

Mind sending a recording of the issue?

**Comment by sakana164** [comment]
> > > > > > hello？are you still there? I need help
> > > > > 
> > > > > 
> > > > > Yes, is the issue still present in version 5.0? If so could you provide a recording?
> > > > 
> > > > 
> > > > Version 5.0，the patch issue in February was what I reported earlier
> > > 
> > > 
> > > Alright, what do you need now?
> > 
> > 
> > After the last feedback, I found that most applications can authorize data, but there are still a few applications that cannot be authorized, such as twitch and discord
> 
> Mind sending a recording of the issue?

Sorry, I didn't express the issue correctly when I entered twitch. Click to authorize, but SAF did not correctly redirect to the data directory of Twitch

https://github.com/Xposed-Modules-Repo/com.github.dan.nostoragerestrict/assets/76257039/62c544a4-02f6-4d62-b1f9-4f5455c1dde3

**Comment by DanGLVK** [comment]
> > > > > > > hello？are you still there? I need help
> > > > > > 
> > > > > > 
> > > > > > Yes, is the issue still present in version 5.0? If so could you provide a recording?
> > > > > 
> > > > > 
> > > > > Version 5.0，the patch issue in February was what I reported earlier
> > > > 
> > > > 
> > > > Alright, what do you need now?
> > > 
> > > 
> > > After the last feedback, I found that most applications can authorize data, but there are still a few applications that cannot be authorized, such as twitch and discord
> > 
> > 
> > Mind sending a recording of the issue?
> 
> Sorry, I didn't express the issue correctly when I entered twitch. Click to authorize, but SAF did not correctly redirect to the data directory of Twitch
> 
>  Screenrecorder-2024-05-17-08-58-21-582.mp4

Can't you navigate to the Folder manually? That doesn't seem like an issue on my module specifically

**Comment by sakana164** [comment]
> > > > > > > > hello？are you still there? I need help
> > > > > > > 
> > > > > > > 
> > > > > > > Yes, is the issue still present in version 5.0? If so could you provide a recording?
> > > > > > 
> > > > > > 
> > > > > > Version 5.0，the patch issue in February was what I reported earlier
> > > > > 
> > > > > 
> > > > > Alright, what do you need now?
> > > > 
> > > > 
> > > > After the last feedback, I found that most applications can authorize data, but there are still a few applications that cannot be authorized, such as twitch and discord
> > > 
> > > 
> > > Mind sending a recording of the issue?
> > 
> > 
> > Sorry, I didn't express the issue correctly when I entered twitch. Click to authorize, but SAF did not correctly redirect to the data directory of Twitch
> > Screenrecorder-2024-05-17-08-58-21-582.mp4
> 
> Can't you navigate to the Folder manually? That doesn't seem like an issue on my module specifically

Yes, but I have already identified the problem. Some applications do not create personal folders in Android/data, nor do they have folders named with package names, so they cannot directly navigate.But the list that requires authorization is displayed incorrectly.
Now I have no problem, thank you very much. You can close the issue now
