### ISSUE TITLE
Doesn't work after latest update of /e/OS (based on LineageOS for microG Android 13).

### ISSUE THREAD

**Issue by bege10** [Xposed-Modules-Repo/com.github.dan.nostoragerestrict#16]
Hello,
this Xposed module worked flawlessly on my phone with Android 13 (Shiftphone 6mq (axolotl), /e/OS-T-dev (based on LineageOS for microG, Android 13).
Since the last system update it doesn't work any more. The folder permission screen looks as without the module, so I cannot grant access to those folders any more that this module should make possible. Apps that had this access before had lost it.
It doesn't make a difference whether I enable the module for the files app or not.

**Comment by DanGLVK** [comment]
> Hello, this Xposed module worked flawlessly on my phone with Android 13 (Shiftphone 6mq (axolotl), /e/OS-T-dev (based on LineageOS for microG, Android 13). Since the last system update it doesn't work any more. The folder permission screen looks as without the module, so I cannot grant access to those folders any more that this module should make possible. Apps that had this access before had lost it. It doesn't make a difference whether I enable the module for the files app or not.

Are you sure you're using the latest version of the module? Also apologies for the delay

**Comment by bege10** [comment]
You've hit the nail on the head. It was not. The LSPosed manager did not show an update. I had to uninstall the module and install the new one. Now it works again. Thank you very much!
