### ISSUE TITLE
Unzip error

### ISSUE THREAD

**Issue by imLotex** [Xposed-Modules-Repo/com.github.dan.nostoragerestrict#18]
When I download the module, it says copying zip to temp directory, then it says unzip error.

**Comment by DanGLVK** [comment]
> When I download the module, it says copying zip to temp directory, then it says unzip error.

Uhh, wrong repo to be reporting this, this is the Lsposed module repo

**Comment by imLotex** [comment]
No? I don't think so at least? I downloaded it and then went to magisk to install it, then the error showed up.

**Comment by DanGLES3** [comment]
> No? I don't think so at least? I downloaded it and then went to magisk to install it, then the error showed up.

This is the xposed modules repo

**Comment by DanGLVK** [comment]
> > No? I don't think so at least? I downloaded it and then went to magisk to install it, then the error showed up.
> 

This is the xposed modules repo, it's written right at the top of the page, also the Magisk version of this module is deprecated and won't be updated (due to issues related to replacing system apps using Magisk modules)

So if you want to use this module in its most updated form you need Lsposed installed

**Comment by imLotex** [comment]
Oh sorry, I'm really new to all of this(I literally just rooted my phone) so idk much about all of this. So, all I need is to download lsposed and then this will work, right?

**Comment by DanGLVK** [comment]
> Oh sorry, I'm really new to all of this(I literally just rooted my phone) so idk much about all of this. So, all I need is to download lsposed and then this will work, right?

Yes, you install Lsposed, then through it you download the module, enable it and reboot

**Comment by imLotex** [comment]
alright, Thank you. I will try that out later.
