### ISSUE TITLE
Urge to update 

### ISSUE THREAD

**Issue by DoraemonPlusPro** [Xposed-Modules-Repo/com.github.dan.nostoragerestrict#2]
Android 13, Use this folder button is accessible,but i can't  see the data folder(it's not hidden
![Screenshot_20221126213514](https://user-images.githubusercontent.com/92413800/204091582-d5e05380-8ece-4996-b657-bd1c3df19907.png)
)

**Comment by DanGLVK** [comment]
> Edit

Update to version 2.0

You should now be able to select the /data /obb folders
