### ISSUE TITLE
Feature Request:Remove the restrictions of SAF on Android/(obb, data) folder.

### ISSUE THREAD

**Issue by daiaji** [Xposed-Modules-Repo/com.github.dan.nostoragerestrict#4]
https://github.com/syncthing/syncthing-android/issues/1883
I was surprised to find that SAF seems to have restrictions on Android/(obb,data).

**Comment by DanGLVK** [comment]
> [syncthing/syncthing-android#1883](https://github.com/syncthing/syncthing-android/issues/1883) I was surprised to find that SAF seems to have restrictions on Android/(obb,data).

I'll look into that, iirc it shouldn't be too hard

**Comment by DanGLVK** [comment]
> [syncthing/syncthing-android#1883](https://github.com/syncthing/syncthing-android/issues/1883) I was surprised to find that SAF seems to have restrictions on Android/(obb,data).

And it's done, check the releases page and download version 2.0 (alternatively the update should show up on Lsposed in a couple hours)
