### ISSUE TITLE
Cannot Access Other SAF Providers

### ISSUE THREAD

**Issue by christantoan** [Xposed-Modules-Repo/com.github.dan.nostoragerestrict#5]
After migrating to the Xposed version, I can no longer access other SAF providers (example: OneDrive and Goggle Drive) with other apps (it's notmal when accessed via Files app directly) when the module is active. It just shows "Can't load content at the moment" message.
![Screenshot_20230611-221116](https://github.com/Xposed-Modules-Repo/com.github.dan.nostoragerestrict/assets/7300310/c11bb53d-b6f4-4cf2-ab38-911e8142ff51)
![Screenshot_20230611-221123](https://github.com/Xposed-Modules-Repo/com.github.dan.nostoragerestrict/assets/7300310/6d853c09-aa25-4192-947f-292b6d230d1f)

Hope this can be fixed.
Thank you.

**Comment by DanGLVK** [comment]
> After migrating to the Xposed version, I can no longer access other SAF providers (example: OneDrive and Goggle Drive) with other apps (it's notmal when accessed via Files app directly) when the module is active. It just shows "Can't load content at the moment" message. ![Screenshot_20230611-221116](https://user-images.githubusercontent.com/7300310/244947468-c11bb53d-b6f4-4cf2-ab38-911e8142ff51.png) ![Screenshot_20230611-221123](https://user-images.githubusercontent.com/7300310/244947472-6d853c09-aa25-4192-947f-292b6d230d1f.png)
> 
> Hope this can be fixed. Thank you.

Odd, i can't replicate this issue here, mind providing some more info? Like Android version and whatnot? Do the logs in the Lsposed app display any erros?

**Comment by DanGLVK** [comment]
Alright, found the issue but not sure how to fix this one at the moment, seems it happens due to the module forcing managed mode to always be on which doesn't seem to play well with third party SAF provider when selecting them, for now either these two workarounds should work 

1-Tapping the box with an arrow icon which goes into the app itself to select the file

2-Not applying the module to the files app

if you could send some logs from your device when this issue happens that'd be great

**Comment by christantoan** [comment]
Sorry I didn't include additional information because I wasn't sure what info are needed. My Android version is Android 11 (variant OxygenOS 11), here are the module and verbose logs from LSPosed when the problem happens (I use Keepass2Android to open a database located in OneDrive using system file picker:
[LSPosed_2023-06-17T08_39_34.761.zip](https://github.com/Xposed-Modules-Repo/com.github.dan.nostoragerestrict/files/11777636/LSPosed_2023-06-17T08_39_34.761.zip)
[LSPosed_2023-06-17T08_39_40.596.zip](https://github.com/Xposed-Modules-Repo/com.github.dan.nostoragerestrict/files/11777637/LSPosed_2023-06-17T08_39_40.596.zip)

Regarding the first workaround, my Files app doesn't have the arrow?
![iMarkup_20230617_084231](https://github.com/Xposed-Modules-Repo/com.github.dan.nostoragerestrict/assets/7300310/960a4658-8144-401b-a616-95b33cc8f4d9)

**Comment by DanGLVK** [comment]
> Sorry I didn't include additional information because I wasn't sure what info are needed. My Android version is Android 11 (variant OxygenOS 11), here are the module and verbose logs from LSPosed when the problem happens (I use Keepass2Android to open a database located in OneDrive using system file picker: [LSPosed_2023-06-17T08_39_34.761.zip](https://github.com/Xposed-Modules-Repo/com.github.dan.nostoragerestrict/files/11777636/LSPosed_2023-06-17T08_39_34.761.zip) [LSPosed_2023-06-17T08_39_40.596.zip](https://github.com/Xposed-Modules-Repo/com.github.dan.nostoragerestrict/files/11777637/LSPosed_2023-06-17T08_39_40.596.zip)
> 
> Regarding the first workaround, my Files app doesn't have the arrow? ![iMarkup_20230617_084231](https://user-images.githubusercontent.com/7300310/246579013-960a4658-8144-401b-a616-95b33cc8f4d9.png)

Alright, yeah, after trying some stuff here, it seems i can't do much about that at the moment, best workaround is only enabling the module to the Files app when first granting an app access to /data or /obb, after that, unapply the module to the Files app and force close it

**Comment by DanGLVK** [comment]
> Sorry I didn't include additional information because I wasn't sure what info are needed. My Android version is Android 11 (variant OxygenOS 11), here are the module and verbose logs from LSPosed when the problem happens (I use Keepass2Android to open a database located in OneDrive using system file picker: [LSPosed_2023-06-17T08_39_34.761.zip](https://github.com/Xposed-Modules-Repo/com.github.dan.nostoragerestrict/files/11777636/LSPosed_2023-06-17T08_39_34.761.zip) [LSPosed_2023-06-17T08_39_40.596.zip](https://github.com/Xposed-Modules-Repo/com.github.dan.nostoragerestrict/files/11777637/LSPosed_2023-06-17T08_39_40.596.zip)
> 
> Regarding the first workaround, my Files app doesn't have the arrow? ![iMarkup_20230617_084231](https://user-images.githubusercontent.com/7300310/246579013-960a4658-8144-401b-a616-95b33cc8f4d9.png)

As an alternative workaround, add Onedrive to Mixplorer, and access it through the up arrow button next to its name

**Comment by christantoan** [comment]
> > Sorry I didn't include additional information because I wasn't sure what info are needed. My Android version is Android 11 (variant OxygenOS 11), here are the module and verbose logs from LSPosed when the problem happens (I use Keepass2Android to open a database located in OneDrive using system file picker: [LSPosed_2023-06-17T08_39_34.761.zip](https://github.com/Xposed-Modules-Repo/com.github.dan.nostoragerestrict/files/11777636/LSPosed_2023-06-17T08_39_34.761.zip) [LSPosed_2023-06-17T08_39_40.596.zip](https://github.com/Xposed-Modules-Repo/com.github.dan.nostoragerestrict/files/11777637/LSPosed_2023-06-17T08_39_40.596.zip)
> > Regarding the first workaround, my Files app doesn't have the arrow? ![iMarkup_20230617_084231](https://user-images.githubusercontent.com/7300310/246579013-960a4658-8144-401b-a616-95b33cc8f4d9.png)
> 
> As an alternative workaround, add Onedrive to Mixplorer, and access it through the up arrow button next to its name

I've just tried that but the OneDrive entry doesn't appear on the sidebar, also pressing the up(/eject?) button also does nothing on other Mixplorer entries.

On other topic, would you recommend this version or the Magisk version more? I've used the Magisk version before and it seemed that it doesn't have this problem. I just migrated to the LSPosed version because Xposed seems more advanced than Magisk :p

**Comment by DanGLVK** [comment]
> > > Sorry I didn't include additional information because I wasn't sure what info are needed. My Android version is Android 11 (variant OxygenOS 11), here are the module and verbose logs from LSPosed when the problem happens (I use Keepass2Android to open a database located in OneDrive using system file picker: [LSPosed_2023-06-17T08_39_34.761.zip](https://github.com/Xposed-Modules-Repo/com.github.dan.nostoragerestrict/files/11777636/LSPosed_2023-06-17T08_39_34.761.zip) [LSPosed_2023-06-17T08_39_40.596.zip](https://github.com/Xposed-Modules-Repo/com.github.dan.nostoragerestrict/files/11777637/LSPosed_2023-06-17T08_39_40.596.zip)
> > > Regarding the first workaround, my Files app doesn't have the arrow? ![iMarkup_20230617_084231](https://user-images.githubusercontent.com/7300310/246579013-960a4658-8144-401b-a616-95b33cc8f4d9.png)
> > 
> > 
> > As an alternative workaround, add Onedrive to Mixplorer, and access it through the up arrow button next to its name
> 
> I've just tried that but the OneDrive entry doesn't appear on the sidebar, also pressing the up(/eject?) button also does nothing on other Mixplorer entries.
> 
> On other topic, would you recommend this version or the Magisk version more? I've used the Magisk version before and it seemed that it doesn't have this problem. I just migrated to the LSPosed version because Xposed seems more advanced than Magisk :p

The Onedrive entry won't appear, you have to access the Mixplorer entry and select the Onedrive files through there

**Comment by DanGLVK** [comment]
> > > Sorry I didn't include additional information because I wasn't sure what info are needed. My Android version is Android 11 (variant OxygenOS 11), here are the module and verbose logs from LSPosed when the problem happens (I use Keepass2Android to open a database located in OneDrive using system file picker: [LSPosed_2023-06-17T08_39_34.761.zip](https://github.com/Xposed-Modules-Repo/com.github.dan.nostoragerestrict/files/11777636/LSPosed_2023-06-17T08_39_34.761.zip) [LSPosed_2023-06-17T08_39_40.596.zip](https://github.com/Xposed-Modules-Repo/com.github.dan.nostoragerestrict/files/11777637/LSPosed_2023-06-17T08_39_40.596.zip)
> > > Regarding the first workaround, my Files app doesn't have the arrow? ![iMarkup_20230617_084231](https://user-images.githubusercontent.com/7300310/246579013-960a4658-8144-401b-a616-95b33cc8f4d9.png)
> > 
> > 
> > As an alternative workaround, add Onedrive to Mixplorer, and access it through the up arrow button next to its name
> 
> I've just tried that but the OneDrive entry doesn't appear on the sidebar, also pressing the up(/eject?) button also does nothing on other Mixplorer entries.
> 
> On other topic, would you recommend this version or the Magisk version more? I've used the Magisk version before and it seemed that it doesn't have this problem. I just migrated to the LSPosed version because Xposed seems more advanced than Magisk :p

As for recommendation, the Lsposed version is just infinitely more reliable, Magisk's method is just crude and not guaranteed to work
