### ISSUE TITLE
Can't download Whatsapp images

### ISSUE THREAD

**Issue by usamaiqbal1177** [Xposed-Modules-Repo/com.github.dan.nostoragerestrict#9]
Thanks a lot for this useful module. It is working fine on other apps which requires folder access.

However, WhatsApp cannot download an image or load a story etc. I have also tried enabling only files app in lsposed module scope as u mentioned in the description. Please see the screenshot for it
![Screenshot_20231031-182752_Shell](https://github.com/Xposed-Modules-Repo/com.github.dan.nostoragerestrict/assets/58624914/4458d886-8842-4ee0-9e52-f4de949b597f)

Please let me know if this is a known issue or some mistake from my side

Looking forward to your kind support. 

Android 13 custom rom Derpfest

**Comment by DanGLVK** [comment]
The description states the opposite, you should ONLY select the Files app in very specific circumstances, otherwise just leave the external storage enabled 

i've also just updated the disclaimer to make it more clear
